In [1]:
dbutils.fs.refreshMounts()

Mounts successfully refreshed.
Out[1]: True

In [2]:
display(dbutils.fs.ls('/mnt/s3data'))

path name size dbfs:/mnt/s3data/hotel_booking_Indexcleaned.parquet/ hotel_booking_Indexcleaned.parquet/ 0 dbfs:/mnt/s3data/hotel_booking_cleaned.parquet/ hotel_booking_cleaned.parquet/ 0 dbfs:/mnt/s3data/hotel_booking_indexencoded.parquet/ hotel_booking_indexencoded.parquet/ 0 dbfs:/mnt/s3data/hotel_bookings.csv hotel_bookings.csv 16855599

In [3]:
import pandas as pd

hotelDF = spark.read.parquet("dbfs:/mnt/s3data/hotel_booking_Indexcleaned.parquet/").toPandas()
display(hotelDF)

is_canceled lead_time arrival_date_year arrival_date_week_number arrival_date_day_of_month stays_in_weekend_nights stays_in_week_nights adults babies is_repeated_guest previous_cancellations previous_bookings_not_canceled booking_changes days_in_waiting_list adr required_car_parking_spaces total_of_special_requests children_num hotel_Index arrival_date_month_Index meal_Index country_Index market_segment_Index reserved_room_type_Index assigned_room_type_Index deposit_type_Index agent_Index company_Index customer_type_Index 0 7 2015 27 1 0 1 1 0 0 0 0 0 0 75.0 0 0 0.0 1.0 1.0 0.0 1.0 3.0 0.0 5.0 0.0 1.0 0.0 0.0 0 13 2015 27 1 0 1 1 0 0 0 0 0 0 75.0 0 0 0.0 1.0 1.0 0.0 1.0 4.0 0.0 0.0 0.0 316.0 0.0 0.0 0 14 2015 27 1 0 2 2 0 0 0 0 0 0 98.0 0 1 0.0 1.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 2.0 0.0 0.0 0 14 2015 27 1 0 2 2 0 0 0 0 0 0 98.0 0 1 0.0 1.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 2.0 0.0 0.0 0 0 2015 27 1 0 2 2 0 0 0 0 0 0 107.0 0 0 0.0 1.0 1.0 0.0 0.0 3.0 5.0 5.0 0.0 1.0 0.0 0.0 0 9 2015 27 1 0 2 2 0 0 0 0 0 0 103.0 0 1 0.0 1.0 1.0 4.0 0.0 3.0 5.0 5.0 0.0 261.0 0.0 0.0 1 85 2015 27 1 0 3 2 0 0 0 0 0 0 82.0 0 1 0.0 1.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 2.0 0.0 0.0 1 75 2015 27 1 0 3 2 0 0 0 0 0 0 105.5 0 0 0.0 1.0 1.0 1.0 0.0 1.0 1.0 1.0 0.0 32.0 0.0 0.0 1 23 2015 27 1 0 4 2 0 0 0 0 0 0 123.0 0 0 0.0 1.0 1.0 0.0 0.0 0.0 2.0 2.0 0.0 2.0 0.0 0.0 0 35 2015 27 1 0 4 2 0 0 0 0 0 0 145.0 0 0 0.0 1.0 1.0 1.0 0.0 0.0 1.0 1.0 0.0 2.0 0.0 0.0 0 68 2015 27 1 0 4 2 0 0 0 0 0 0 97.0 0 3 0.0 1.0 1.0 0.0 10.0 0.0 1.0 2.0 0.0 2.0 0.0 0.0 0 18 2015 27 1 0 4 2 0 0 0 0 1 0 154.77 0 1 1.0 1.0 1.0 1.0 3.0 0.0 4.0 4.0 0.0 8.0 0.0 0.0 0 37 2015 27 1 0 4 2 0 0 0 0 0 0 94.71 0 0 0.0 1.0 1.0 0.0 0.0 0.0 2.0 2.0 0.0 8.0 0.0 0.0 0 68 2015 27 1 0 4 2 0 0 0 0 0 0 97.0 0 3 0.0 1.0 1.0 0.0 6.0 0.0 1.0 2.0 0.0 2.0 0.0 0.0 0 37 2015 27 1 0 4 2 0 0 0 0 0 0 97.5 0 0 0.0 1.0 1.0 0.0 0.0 1.0 2.0 2.0 0.0 10.0 0.0 2.0 0 12 2015 27 1 0 1 2 0 0 0 0 0 0 88.2 0 0 0.0 1.0 1.0 0.0 6.0 0.0 0.0 2.0 0.0 2.0 0.0 0.0 0 0 2015 27 1 0 1 2 0 0 0 0 0 0 107.42 0 0 0.0 1.0 1.0 0.0 2.0 4.0 0.0 4.0 0.0 1.0 20.0 0.0 0 7 2015 27 1 0 4 2 0 0 0 0 0 0 153.0 0 1 0.0 1.0 1.0 0.0 1.0 3.0 4.0 4.0 0.0 7.0 0.0 0.0 0 37 2015 27 1 1 4 1 0 0 0 0 0 0 97.29 0 1 0.0 1.0 1.0 0.0 1.0 0.0 3.0 3.0 0.0 8.0 0.0 0.0 0 72 2015 27 1 2 4 2 0 0 0 0 1 0 84.67 0 1 0.0 1.0 1.0 0.0 0.0 3.0 0.0 0.0 0.0 7.0 0.0 0.0 0 72 2015 27 1 2 4 2 0 0 0 0 1 0 84.67 0 1 0.0 1.0 1.0 0.0 0.0 3.0 0.0 0.0 0.0 7.0 0.0 0.0 0 72 2015 27 1 2 4 2 0 0 0 0 1 0 99.67 0 1 0.0 1.0 1.0 0.0 0.0 3.0 1.0 1.0 0.0 7.0 0.0 0.0 0 127 2015 27 1 2 5 2 0 0 0 0 0 0 94.95 0 1 0.0 1.0 1.0 1.0 1.0 1.0 1.0 8.0 0.0 52.0 0.0 2.0 0 78 2015 27 1 2 5 2 0 0 0 0 0 0 63.6 1 0 0.0 1.0 1.0 0.0 0.0 1.0 1.0 1.0 0.0 40.0 0.0 0.0 0 48 2015 27 1 2 5 2 0 0 0 0 0 0 79.5 0 0 0.0 1.0 1.0 0.0 6.0 1.0 1.0 1.0 0.0 10.0 0.0 2.0 1 60 2015 27 1 2 5 2 0 0 0 0 0 0 107.0 0 2 0.0 1.0 1.0 0.0 0.0 0.0 2.0 2.0 0.0 2.0 0.0 0.0 0 77 2015 27 1 2 5 2 0 0 0 0 0 0 94.0 0 0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 2.0 0.0 0.0 0 99 2015 27 1 2 5 2 0 0 0 0 0 0 87.3 1 1 0.0 1.0 1.0 0.0 0.0 0.0 1.0 1.0 0.0 2.0 0.0 0.0 0 118 2015 27 1 4 10 1 0 0 0 0 2 0 62.0 0 2 0.0 1.0 1.0 0.0 21.0 3.0 0.0 0.0 0.0 1.0 0.0 0.0 0 95 2015 27 1 4 11 2 0 0 0 0 0 0 63.86 0 0 0.0 1.0 1.0 0.0 1.0 1.0 1.0 1.0 0.0 8.0 0.0 0.0 1 96 2015 27 1 2 8 2 0 0 0 0 0 0 108.3 0 2 0.0 1.0 1.0 0.0 0.0 3.0 2.0 2.0 0.0 1.0 0.0 0.0 0 69 2015 27 2 2 4 2 0 0 0 0 0 0 65.5 0 0 0.0 1.0 1.0 0.0 6.0 1.0 0.0 5.0 0.0 57.0 0.0 0.0 1 45 2015 27 2 1 3 3 0 0 0 0 0 0 108.8 0 1 0.0 1.0 1.0 0.0 0.0 0.0 1.0 1.0 0.0 8.0 0.0 0.0 1 40 2015 27 2 1 3 3 0 0 0 0 0 0 108.8 0 1 0.0 1.0 1.0 0.0 0.0 0.0 1.0 1.0 0.0 8.0 0.0 0.0 0 15 2015 27 2 1 3 2 0 0 0 0 0 0 98.0 0 0 0.0 1.0 1.0 0.0 3.0 0.0 0.0 5.0 0.0 2.0 0.0 0.0 0 36 2015 27 2 1 3 3 0 0 0 0 0 0 108.8 0 1 0.0 1.0 1.0 0.0 0.0 0.0 1.0 1.0 0.0 8.0 0.0 0.0 1 43 2015 27 2 1 3 3 0 0 0 0 0 0 108.8 0 0 0.0 1.0 1.0 0.0 0.0 0.0 1.0 1.0 0.0 8.0 0.0 0.0 0 70 2015 27 2 2 3 2 0 0 0 0 0 0 137.0 0 1 0.0 1.0 1.0 1.0 20.0 3.0 2.0 2.0 0.0 7.0 0.0 0.0 1 45 2015 27 2 

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(hotelDF.drop(["is_canceled"], axis=1), hotelDF[["is_canceled"]].values.ravel(), test_size = 0.25, random_state=42)

#### Train the model

In [6]:
import mlflow.sklearn
from sklearn.ensemble import RandomForestClassifier
rf_hotel = RandomForestClassifier(n_estimators=100, criterion='gini', max_depth=None, bootstrap=True) 

Sat May 2 11:09:39 2020 py4j imported

In [7]:
from sklearn.metrics import accuracy_score,recall_score,confusion_matrix
rf_hotel.fit(X_train, y_train)
test_pred = rf_hotel.predict(X_test)
print(confusion_matrix(y_test,test_pred))
print(accuracy_score(y_test,test_pred))

[[17187 1208]
 [ 1867 9033]]
0.8950332821300563

#### Cross validation by estimators

In [9]:
from sklearn.model_selection import KFold, cross_val_score
n_folds = 5
def acc_cv(model):
    kf = KFold(n_folds, shuffle=True,
               random_state=42).get_n_splits(X_train)
    acc = cross_val_score(model, X_train, y_train,scoring="accuracy", cv=kf)
    return (acc)

In [10]:
import numpy as np
import mlflow.sklearn
from sklearn.ensemble import RandomForestClassifie
from sklearn.metrics import accuracy_score

acc_estimator=[]
for i in [10,100,400,700,1000,2000]:
  rf = RandomForestClassifier(n_estimators=i, max_depth=5)
  rf.fit(X_train, y_train)
  score = acc_cv(rf)
  acc_estimator.append(score)

In [11]:
  acc_estimator

Out[12]: [array([0.79382147, 0.78773397, 0.78403596, 0.77981338, 0.77133591]),
 array([0.77629857, 0.802014 , 0.77487626, 0.79124943, 0.80251479]),
 array([0.78989589, 0.78483245, 0.77646925, 0.7728721 , 0.77765134]),
 array([0.7806224 , 0.77823292, 0.78124822, 0.77890305, 0.78026855]),
 array([0.78193093, 0.78267054, 0.77624168, 0.77810651, 0.77600137]),
 array([0.77772089, 0.77891563, 0.7776071 , 0.78004096, 0.77600137])]

In [12]:
avg_acc_estimator = []
for i in range(6):
  avg_acc_estimator.append( acc_estimator[i].mean())
avg_acc_estimator

Out[25]: [0.7833481384683905,
 0.789390610049769,
 0.7803442057625427,
 0.7798550284075512,
 0.7789902043337814,
 0.7780571888528243]

#### Cross validation by depth

In [14]:
import numpy as np
import mlflow.sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

acc_depth=[]
for i in [5,10,20,30,40,50,60,70,80,100]:
  rf = RandomForestClassifier(n_estimators=100, max_depth=i)
  rf.fit(X_train, y_train)
  score = acc_cv(rf)
  acc_depth.append(score)

In [15]:
acc_depth ##5 folds

Out[23]: [array([0.78875804, 0.79040792, 0.7822154 , 0.77406691, 0.78612881]),
 array([0.85805314, 0.85919099, 0.85993059, 0.8548589 , 0.85656577]),
 array([0.88900267, 0.89099391, 0.8903112 , 0.88654984, 0.88865498]),
 array([0.89093702, 0.89372475, 0.89366786, 0.8911015 , 0.89235321]),
 array([0.88979917, 0.89435057, 0.89230244, 0.89138598, 0.8911015 ]),
 array([0.89156284, 0.89395232, 0.89361097, 0.89093081, 0.89144288]),
 array([0.89105081, 0.89469193, 0.89440746, 0.8911584 , 0.892467 ]),
 array([0.89065256, 0.89361097, 0.8933834 , 0.89161356, 0.89286527]),
 array([0.88979917, 0.89474882, 0.89241623, 0.89138598, 0.89218252]),
 array([0.89150595, 0.89503328, 0.89241623, 0.8898498 , 0.89263769])]

In [16]:
avg_acc_depth = []
for i in range(10):
  avg_acc_depth.append( acc_depth[i].mean())
avg_acc_depth

Out[26]: [0.7843154144133975,
 0.8577198773928429,
 0.8891025226696794,
 0.8923568692576772,
 0.8917879329519591,
 0.8922999644272789,
 0.8927551189099194,
 0.892425151946689,
 0.8921065434204074,
 0.8922885872160542]

##### Test accuracy of best rf

In [18]:
from sklearn.metrics import accuracy_score,recall_score,confusion_matrix
rf = RandomForestClassifier(n_estimators=100, max_depth=60)
rf_hotel.fit(X_train, y_train)
test_pred = rf_hotel.predict(X_test)
print(confusion_matrix(y_test,test_pred))
print(accuracy_score(y_test,test_pred))

[[17154 1241]
 [ 1844 9056]]
0.8946919269499914

####Grid search

In [20]:
#define accuracy as the criteria for grid search
import mlflow.sklearn
from sklearn.metrics import accuracy_score, make_scorer
import numpy as np

def custom_loss(actual,preds):
   rf_hotel.fit(X_train, y_train)
   test_pred = rf_hotel.predict(X_test)
   predictions_class =  np.where(preds>0.5, 1, 0)
   acc_rf = accuracy_score(actual, predictions_class)
   return acc_rf
custom_scorer = make_scorer(custom_loss,greater_is_better=True)

In [21]:
import mlflow.sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, make_scorer
import numpy as np
# dictionary containing hyperparameter names and list of values we want to try
parameters = {'n_estimators': [10, 100, 200, 500, 1000] , 
              'max_depth': [None, 10,50,100,200,500], 
              'bootstrap': [False, True]}

rf = RandomForestClassifier()
grid_rf_model = GridSearchCV(rf, parameters,scoring='accuracy', cv=5, n_jobs=-1)
grid_rf_model.fit(X_train, y_train)

best_rf = grid_rf_model.best_estimator_
for p in parameters:
  print("Best '{}': {}".format(p, best_rf.get_params()[p]))

Best 'n_estimators': 1000
Best 'max_depth': None
Best 'bootstrap': True

In [22]:
from sklearn.metrics import accuracy_score,recall_score,confusion_matrix
test_pred = best_rf.predict(X_test)
print(confusion_matrix(y_test,test_pred))
print(accuracy_score(y_test,test_pred))

[[17182 1213]
 [ 1837 9063]]
0.8958866700802185

#### Feature Importance

In [24]:
names=hotelDF.columns[1:]
Feature = sorted(zip(map(lambda x: round(x, 4), best_rf.feature_importances_), names), reverse=True)
for i in Feature:
    print(i)
Best_RFdict = dict(Feature)

(0.1238, 'deposit_type_Index')
(0.1235, 'lead_time')
(0.1229, 'country_Index')
(0.0695, 'adr')
(0.0635, 'agent_Index')
(0.0603, 'total_of_special_requests')
(0.0512, 'arrival_date_day_of_month')
(0.0479, 'arrival_date_week_number')
(0.042, 'market_segment_Index')
(0.0335, 'stays_in_week_nights')
(0.0326, 'previous_cancellations')
(0.0279, 'arrival_date_month_Index')
(0.0245, 'customer_type_Index')
(0.0238, 'required_car_parking_spaces')
(0.0235, 'assigned_room_type_Index')
(0.0235, 'arrival_date_year')
(0.0217, 'stays_in_weekend_nights')
(0.0201, 'booking_changes')
(0.0137, 'reserved_room_type_Index')
(0.0117, 'meal_Index')
(0.0115, 'adults')
(0.0083, 'hotel_Index')
(0.0053, 'children_num')
(0.0048, 'previous_bookings_not_canceled')
(0.0047, 'company_Index')
(0.0019, 'is_repeated_guest')
(0.0017, 'days_in_waiting_list')
(0.0007, 'babies')

In [25]:
import matplotlib.pyplot as plt 
import pandas as pd 
import seaborn as sns

sns.set(rc={'figure.figsize':(25,6)})
axis = sns.barplot(x=list(Best_RFdict.values()), y=list(Best_RFdict.keys()))
axis.set_title("The Importance of Feature",fontsize= 20)
axis.set_ylabel('Importance',fontsize=15)
plt.xticks(rotation='vertical');

for p in axis.patches:
    height = p.get_height()
    axis.annotate('{}'.format(height),xy=(p.get_x() + p.get_width() / 2, height), ha='center', va='bottom',fontsize=10)

display(axis)

In [26]:
try:
  dbutils.fs.unmount('/mnt/s3data') 
except:
  print("/mnt/s3data has been unmounted")